const ACTION_TYPES = {
  WORKINING_USER_REQUEST: 'WORKINING_USER_REQUEST',
  WORKINING_USER_SUCCESS: 'WORKINING_USER_SUCCESS',
  WORKINING_USER_ERROR: 'WORKINING_USER_ERROR',
  };
  
  export default ACTION_TYPES;
  