const ACTION_TYPES = {
  WORKINING_USER_REQUEST: 'WORKINING_USER_REQUEST',
  WORKINING_USER_SUCCESS: 'WORKINING_USER_SUCCESS',
  WORKINING_USER_ERROR: 'WORKINING_USER_ERROR',
  
  CREATE_WORKER_REQUEST: 'CREATE_WORKER_REQUEST',
  CREATE_WORKER_SUCCESS: 'CREATE_WORKER_SUCCESS',
  CREATE_WORKER_ERROR: 'CREATE_WORKER_ERROR',
  CLEAR_DATA: 'CLEAR_DATA',

  GET_TOKEN_REQUEST: 'GET_TOKEN_REQUEST',
  GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS',
  GET_TOKEN_ERROR: 'GET_TOKEN_ERROR',

  GET_POSITION_REQUEST: 'GET_POSITION_REQUEST',
  GET_POSITION_SUCCESS: 'GET_POSITION_SUCCESS',
  GET_POSITION_ERROR: 'GET_POSITION_ERROR',
  };
  
  export default ACTION_TYPES;
  